---
title: "Gantt Chart"
output: html_document
---

### GANTT CHART OF RCT DATA

#### Process data for Gantt Chart

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(googleVis)
library(janitor)
library(readr)
library(stringr)
library(tidyverse)
library(timevis)
library(XML)


```


First, let's extract dates from the CSV file

``` {r Extract_data}
# Extract data 
results = read_csv("Data/SearchResultsTable.csv") %>%
  clean_names()  

```

``` {r get start and end dates }

gantt_data = results %>%
  mutate(
    mm_start   = str_sub(start_date,  1,  3), # Extract month
    yy_start   = str_sub(start_date, -4, -1), # Extract 4-digit year
    date_start = as.Date(paste(yy_start, mm_start, "01", sep = "-"), "%Y-%b-%d"),
    mm_end     = str_sub(completion_date,  1,  3),
    yy_end     = str_sub(completion_date, -4, -1),
    date_end   = as.Date(paste(yy_end,   mm_end,   "01", sep = "-"), "%Y-%b-%d"),
    n_locations = str_count(locations , "\\|"),
    n_treatments = str_count(interventions, "\\|"),
    label = ifelse(acronym == "null", title, acronym)
    ) %>%
  select(nct_number, title, acronym, date_start, date_end, n_locations, n_treatments,
           phases, study_type, label, recruitment) %>%
  filter(!is.na(date_start) & !is.na(date_end))%>%
  select(label, everything()) %>%
  #Sort by date
  arrange(date_start)


toplot <- gantt_data %>%
      filter(study_type == "Observational")
    
    timeline = gvisTimeline(data = toplot,
                            rowlabel = "nct_number",
                            barlabel = "label",
                            start = "date_start",
                            end = "date_end",
                            options = list(height = 600), colors(distinct = FALSE))
    plot(timeline)

testdata = gantt_data %>%
  filter(!is.na(date_start) & !is.na(date_end)) %>%
  mutate(label = ifelse(acronym == "null", title, acronym),
         ) %>%
  #.[1:10,] %>%
  arrange(date_start) %>%
  filter(date_start >= "2010-01-01" )

nrow(testdata)
  
timeline = gvisTimeline(data=testdata,
                        rowlabel = "nct_number",
                        barlabel = "label",
                        start = "date_start",
                        end = "date_end",
                        options = list(height = 600), colors(distinct = FALSE))

plot(timeline)

```

