---
title: "Gantt Chart"
output: html_document
---

### GANTT CHART OF RCT DATA

#### Process data for Gantt Chart

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(googleVis)
library(janitor)
library(readr)
library(stringr)
library(tidyverse)
library(timevis)
library(XML)


```


First, let's extract dates from the CSV file

``` {r Extract_data}
# Extract data 
#results = read_csv("data/searchresultstable.csv") %>%
  results = read_csv("Data/SearchResultsTable.csv") %>%
  clean_names()  

names(results)
```

``` {r get start and end dates }

# Determine number of variables to create for location
nlocs = str_count(results$locations , "\\|") %>%
  max(na.rm = TRUE)

# Determine number of variables to create for interventions
ntreatment = str_count(results$interventions, "\\|") %>%
  max(na.rm = TRUE)

gantt_data = results %>%
  mutate(
    mm_start   = str_sub(start_date,  1,  3), # Extract month
    yy_start   = str_sub(start_date, -4, -1), # Extract 4-digit year
    date_start = as.Date(paste(yy_start, mm_start, "01", sep = "-"), "%Y-%b-%d"),
    mm_end     = str_sub(completion_date,  1,  3),
    yy_end     = str_sub(completion_date, -4, -1),
    date_end   = as.Date(paste(yy_end,   mm_end,   "01", sep = "-"), "%Y-%b-%d"),
    n_locations = str_count(locations , "\\|"),
    n_treatments = str_count(interventions, "\\|"),
    label = ifelse(acronym == "null", title, acronym)
    ) %>%
  select(nct_number, title, acronym, date_start, date_end, n_locations, n_treatments,
           phases, study_type, label, recruitment) %>%
  filter(!is.na(date_start) & !is.na(date_end))%>%
  select(label, everything())


# Save data to Data directory
saveRDS(gantt_data, "data/gantt_data.rds")


str(gantt_data)  
View(gantt_data)
names(gantt_data)



 toplot <- gantt_data %>%
      filter(study_type == "Observational")
    
    timeline = gvisTimeline(data = toplot,
                            rowlabel = "nct_number",
                            barlabel = "label",
                            start = "date_start",
                            end = "date_end",
                            options = list(height = 600))
    plot(timeline)

testdata = gantt_data %>%
  filter(!is.na(date_start) & !is.na(date_end)) %>%
  mutate(label = ifelse(acronym == "null", title, acronym),
         ) %>%
  #.[1:10,] %>%
  arrange(date_start) %>%
  filter(date_start >= "2010-01-01" )
  
timeline = gvisTimeline(data=testdata,
                        rowlabel = "nct_number",
                        barlabel = "label",
                        start = "date_start",
                        end = "date_end",
                        options = list(height = 600))

plot(timeline)

```


```{r}
datTL <- data.frame(Position=c(rep("President", 3), rep("Vice", 3)),
                    Name=c("Washington", "Adams", "Jefferson",
                           "Adams", "Jefferson", "Burr"),
                    start=as.Date(x=rep(c("1789-03-29", "1797-02-03", 
                                          "1801-02-03"),2)),
                    end=as.Date(x=rep(c("1797-02-03", "1801-02-03", 
                                        "1809-02-03"),2)))
Timeline <- gvisTimeline(data=datTL, 
                         rowlabel="Name",
                         barlabel="Position",
                         start="start", 
                         end="end",
                         options = list(height=350)) 

,
                         options=list(timeline="{groupByRowLabel:false}",
                                      backgroundColor='#ffd', 
                                      height=350,
                                      colors="['#cbb69d', '#603913', '#c69c6e']"))
plot(Timeline)

```

